const cities = [
  { id: "01001", city: "Alegría-Dulantzi", province: "Araba/Álava" },
  { id: "01002", city: "Amurrio", province: "Araba/Álava" },
  { id: "01003", city: "Aramaio", province: "Araba/Álava" },
  { id: "01004", city: "Artziniega", province: "Araba/Álava" },
  { id: "01006", city: "Armiñón", province: "Araba/Álava" },
  { id: "01008", city: "Arratzua-Ubarrundia", province: "Araba/Álava" },
  { id: "01009", city: "Asparrena", province: "Araba/Álava" },
  { id: "01010", city: "Ayala/Aiara", province: "Araba/Álava" },
  { id: "01011", city: "Baños de Ebro/Mañueta", province: "Araba/Álava" },
  { id: "01013", city: "Barrundia", province: "Araba/Álava" },
  { id: "01014", city: "Berantevilla", province: "Araba/Álava" },
  { id: "01016", city: "Bernedo", province: "Araba/Álava" },
  { id: "01017", city: "Campezo/Kanpezu", province: "Araba/Álava" },
  { id: "01018", city: "Zigoitia", province: "Araba/Álava" },
  { id: "01019", city: "Kripan", province: "Araba/Álava" },
  { id: "01020", city: "Kuartango", province: "Araba/Álava" },
  { id: "01021", city: "Elburgo/Burgelu", province: "Araba/Álava" },
  { id: "01042", city: "Okondo", province: "Araba/Álava" },
  { id: "01043", city: "Oyón-Oion", province: "Araba/Álava" },
  { id: "01044", city: "Peñacerrada-Urizaharra", province: "Araba/Álava" },
  { id: "01046", city: "Erriberagoitia/Ribera Alta", province: "Araba/Álava" },
  { id: "01047", city: "Ribera Baja/Erribera Beitia", province: "Araba/Álava" },
  { id: "01049", city: "Añana", province: "Araba/Álava" },
  { id: "01051", city: "Agurain/Salvatierra", province: "Araba/Álava" },
  { id: "01052", city: "Samaniego", province: "Araba/Álava" },
  { id: "01053", city: "San Millán/Donemiliaga", province: "Araba/Álava" },
  { id: "01054", city: "Urkabustaiz", province: "Araba/Álava" },
  { id: "01055", city: "Valdegovía/Gaubea", province: "Araba/Álava" },
  { id: "01056", city: "Harana/Valle de Arana", province: "Araba/Álava" },
  {
    id: "01057",
    city: "Villabuena de Álava/Eskuernaga",
    province: "Araba/Álava",
  },
  { id: "01058", city: "Legutio", province: "Araba/Álava" },
  { id: "01059", city: "Vitoria-Gasteiz", province: "Araba/Álava" },
  { id: "01060", city: "Yécora/Iekora", province: "Araba/Álava" },
  { id: "01061", city: "Zalduondo", province: "Araba/Álava" },
  { id: "01062", city: "Zambrana", province: "Araba/Álava" },
  { id: "01063", city: "Zuia", province: "Araba/Álava" },
  { id: "27028  ", city: "Lugo", province: "Lugo" },
];

export default cities;
