const cities = [
  { id: "01001", city: "Alegría-Dulantzi", province: "Araba/Álava" },
  { id: "01002", city: "Amurrio", province: "Araba/Álava" },
  { id: "01003", city: "Aramaio", province: "Araba/Álava" },
  { id: "01004", city: "Artziniega", province: "Araba/Álava" },
  { id: "01006", city: "Armiñón", province: "Araba/Álava" },
  { id: "01008", city: "Arratzua-Ubarrundia", province: "Araba/Álava" },
  { id: "01009", city: "Asparrena", province: "Araba/Álava" },
  { id: "01010", city: "Ayala/Aiara", province: "Araba/Álava" },
  { id: "01011", city: "Baños de Ebro/Mañueta", province: "Araba/Álava" },
  { id: "01013", city: "Barrundia", province: "Araba/Álava" },
  { id: "01014", city: "Berantevilla", province: "Araba/Álava" },
  { id: "01016", city: "Bernedo", province: "Araba/Álava" },
  { id: "01017", city: "Campezo/Kanpezu", province: "Araba/Álava" },
  { id: "01018", city: "Zigoitia", province: "Araba/Álava" },
  { id: "01019", city: "Kripan", province: "Araba/Álava" },
  { id: "01020", city: "Kuartango", province: "Araba/Álava" },
  { id: "01021", city: "Elburgo/Burgelu", province: "Araba/Álava" },
  { id: "01022", city: "Elciego", province: "Araba/Álava" },
  { id: "01023", city: "Elvillar/Bilar", province: "Araba/Álava" },
  { id: "01027", city: "Iruraiz-Gauna", province: "Araba/Álava" },
  { id: "01028", city: "Labastida/Bastida", province: "Araba/Álava" },
  { id: "01030", city: "Lagr�n", province: "Araba/Álava" },
  { id: "01031", city: "Laguardia", province: "Araba/Álava" },
  { id: "01032", city: "Lanciego/Lantziego", province: "Araba/Álava" },
  { id: "01033", city: "Lapuebla de Labarca", province: "Araba/Álava" },
  { id: "01034", city: "Leza", province: "Araba/Álava" },
  { id: "01036", city: "Laudio/Llodio", province: "Araba/Álava" },
  { id: "01037", city: "Arraia-Maeztu", province: "Araba/Álava" },
  {
    id: "01039",
    city: "Moreda de Álava/Moreda Araba",
    province: "Araba/Álava",
  },
  { id: "01041", city: "Navaridas", province: "Araba/Álava" },
  { id: "01042", city: "Okondo", province: "Araba/Álava" },
  { id: "01043", city: "Oyón-Oion", province: "Araba/Álava" },
  { id: "01044", city: "Peñacerrada-Urizaharra", province: "Araba/Álava" },
  { id: "01046", city: "Erriberagoitia/Ribera Alta", province: "Araba/Álava" },
  { id: "01047", city: "Ribera Baja/Erribera Beitia", province: "Araba/Álava" },
  { id: "01049", city: "Añana", province: "Araba/Álava" },
  { id: "01051", city: "Agurain/Salvatierra", province: "Araba/Álava" },
  { id: "01052", city: "Samaniego", province: "Araba/Álava" },
  { id: "01053", city: "San Millán/Donemiliaga", province: "Araba/Álava" },
  { id: "01054", city: "Urkabustaiz", province: "Araba/Álava" },
  { id: "01055", city: "Valdegovía/Gaubea", province: "Araba/Álava" },
  { id: "01056", city: "Harana/Valle de Arana", province: "Araba/Álava" },
  {
    id: "01057",
    city: "Villabuena de Álava/Eskuernaga",
    province: "Araba/Álava",
  },
  { id: "01058", city: "Legutio", province: "Araba/Álava" },
  { id: "01059", city: "Vitoria-Gasteiz", province: "Araba/Álava" },
  { id: "01060", city: "Yécora/Iekora", province: "Araba/Álava" },
  { id: "01061", city: "Zalduondo", province: "Araba/Álava" },
  { id: "01062", city: "Zambrana", province: "Araba/Álava" },
  { id: "01063", city: "Zuia", province: "Araba/Álava" },
  { id: "01901", city: "Iru�a Oka/Iru�a de Oca", province: "Araba/Álava" },
  { id: "01902", city: "Lantar�n", province: "Araba/Álava" },
  { id: "02001", city: "Abengibre", province: "Albacete" },
  { id: "02002", city: "Alatoz", province: "Albacete" },
  { id: "02003", city: "Albacete", province: "Albacete" },
  { id: "02004", city: "Albatana", province: "Albacete" },
  { id: "02005", city: "Alborea", province: "Albacete" },
  { id: "02006", city: "Alcadozo", province: "Albacete" },
  { id: "02007", city: "Alcal� del J�car", province: "Albacete" },
  { id: "02008", city: "Alcaraz", province: "Albacete" },
  { id: "02009", city: "Almansa", province: "Albacete" },
  { id: "02010", city: "Alpera", province: "Albacete" },
  { id: "02011", city: "Ayna", province: "Albacete" },
  { id: "02012", city: "Balazote", province: "Albacete" },
  { id: "02013", city: "Balsa de Ves", province: "Albacete" },
  { id: "02014", city: "Ballestero, El", province: "Albacete" },
  { id: "02015", city: "Barrax", province: "Albacete" },
  { id: "02016", city: "Bienservida", province: "Albacete" },
  { id: "02017", city: "Bogarra", province: "Albacete" },
  { id: "02018", city: "Bonete", province: "Albacete" },
  { id: "02019", city: "Bonillo, El", province: "Albacete" },
  { id: "02020", city: "Carcel�n", province: "Albacete" },
  { id: "02036", city: "Golosalvo", province: "Albacete" },
  { id: "02037", city: "Hell�n", province: "Albacete" },
  { id: "02038", city: "Herrera, La", province: "Albacete" },
  { id: "02039", city: "Higueruela", province: "Albacete" },
  { id: "02040", city: "Hoya-Gonzalo", province: "Albacete" },
  { id: "02041", city: "Jorquera", province: "Albacete" },
  { id: "02042", city: "Letur", province: "Albacete" },
  { id: "02043", city: "Lezuza", province: "Albacete" },
  { id: "02044", city: "Li�tor", province: "Albacete" },
  { id: "02045", city: "Madrigueras", province: "Albacete" },
  { id: "02046", city: "Mahora", province: "Albacete" },
  { id: "02047", city: "Masegoso", province: "Albacete" },
  { id: "02048", city: "Minaya", province: "Albacete" },
  { id: "02049", city: "Molinicos", province: "Albacete" },
  { id: "02050", city: "Montalvos", province: "Albacete" },
  { id: "02051", city: "Montealegre del Castillo", province: "Albacete" },
  { id: "02052", city: "Motilleja", province: "Albacete" },
  { id: "02053", city: "Munera", province: "Albacete" },
  { id: "02054", city: "Navas de Jorquera", province: "Albacete" },
  { id: "02055", city: "Nerpio", province: "Albacete" },
  { id: "02056", city: "Ontur", province: "Albacete" },
  { id: "02057", city: "Ossa de Montiel", province: "Albacete" },
  { id: "02058", city: "Paterna del Madera", province: "Albacete" },
  { id: "02059", city: "Pe�ascosa", province: "Albacete" },
  { id: "02064", city: "Pozo-Lorente", province: "Albacete" },
  { id: "02065", city: "Pozuelo", province: "Albacete" },
  { id: "02066", city: "Recueja, La", province: "Albacete" },
  { id: "02067", city: "Ri�par", province: "Albacete" },
  { id: "02068", city: "Robledo", province: "Albacete" },
  { id: "02069", city: "Roda, La", province: "Albacete" },
  { id: "02070", city: "Salobre", province: "Albacete" },
  { id: "02071", city: "San Pedro", province: "Albacete" },
  { id: "02072", city: "Socovos", province: "Albacete" },
  { id: "02073", city: "Tarazona de la Mancha", province: "Albacete" },
  { id: "02074", city: "Tobarra", province: "Albacete" },
  { id: "02075", city: "Valdeganga", province: "Albacete" },
  { id: "02076", city: "Vianos", province: "Albacete" },
  { id: "02077", city: "Villa de Ves", province: "Albacete" },
  { id: "02078", city: "Villalgordo del J�car", province: "Albacete" },
  { id: "02079", city: "Villamalea", province: "Albacete" },
  { id: "02080", city: "Villapalacios", province: "Albacete" },
  { id: "02081", city: "Villarrobledo", province: "Albacete" },
  { id: "02082", city: "Villatoya", province: "Albacete" },
  { id: "02083", city: "Villavaliente", province: "Albacete" },
  { id: "02084", city: "Villaverde de Guadalimar", province: "Albacete" },
  { id: "02085", city: "Viveros", province: "Albacete" },
  { id: "02086", city: "Yeste", province: "Albacete" },
  { id: "15078", city: "Santiago de Compostela", province: "A coruña" },
  { id: "27028  ", city: "Lugo", province: "Lugo" },
];

export default cities;
